name: crossdrop
description: "Cross-Platform LAN and VPN Data Transfer App for Windows, Linux, and Android"
publish_to: 'none'
version: 1.1.0+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  file_picker: ^10.3.3
  path_provider: ^2.1.2
  open_filex: ^4.4.0
  device_info_plus: ^10.1.0
  crypto: ^3.0.3
  uuid: ^4.3.3
  intl: ^0.19.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
