from datetime import datetime
from sqlalchemy import create_engine, Column, Integer, String, Boolean, DateTime, ForeignKey, Text
from sqlalchemy.orm import declarative_base, sessionmaker, relationship
from app.config import DATABASE_URL

# SQLite connect args
connect_args = {"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {}

engine = create_engine(DATABASE_URL, connect_args=connect_args)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String(255), unique=True, index=True, nullable=False)
    username = Column(String(100), unique=True, index=True, nullable=False)
    hashed_password = Column(String(255), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    devices = relationship("Device", back_populates="owner", cascade="all, delete-orphan")

class Device(Base):
    __tablename__ = "devices"

    id = Column(String(64), primary_key=True, index=True) # UUID generated by device client
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    name = Column(String(128), nullable=False) # e.g. "Work PC", "Pixel 8", "Home Debian"
    platform = Column(String(32), nullable=False) # "windows", "linux", "android"
    
    # Network endpoints reported by client
    local_ips = Column(Text, default="[]") # JSON list of IPv4 strings, e.g. ["192.168.1.50"]
    vpn_ips = Column(Text, default="[]") # JSON list of VPN IPv4 strings, e.g. ["10.8.0.2", "100.64.0.5"]
    transfer_port = Column(Integer, default=52520)
    
    # Presence & Heartbeat
    last_seen = Column(DateTime, default=datetime.utcnow)
    is_online = Column(Boolean, default=True)

    owner = relationship("User", back_populates="devices")

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

def init_db():
    Base.metadata.create_all(bind=engine)
